const Discord = require ("discord.js");

exports.run = (client, message) => {
const lembed = new Discord.RichEmbed()
.setColor("#5ab1bb")
.setTitle(" Seviye Sistemi Komutları ")
.addField("!seviye","Seviyeni Görebilirsin!")
.addField(" !seviye (random kişi) " , "Sunucu İçinde Etiketlediğin Kişinin Seviyesini Görürsün.")
.addField(" !seviyeyardım " , "Seviye Yardım Komutlarını Gösterir.")
message.channel.sendEmbed(lembed)
.then; 
const mhelp = new Discord.RichEmbed()
.setColor("#5ab1bb")
.setTitle("Moderasyon Komutları")
.setThumbnail("https://i.imgur.com/JsgxK3Y.png")
.addField("!afk (sebep)", "Sunucuda Afk Olursunuz Ve Biri Sizi Etiketlerse Bot Otomatik Olarak Girdiğiniz Sebebi Gösterir.")
.addField("!anket (konu,mesaj)", "Bulunduğunuz Kanalda Anket Oluşturursunuz.")
.addField("!anti-spam [aç/kapat]" , "Bulunduğunuz Kanalda Anti-Spam Özelliğini Aktif Eder.")
.addField("!bot-izin [botid]", "Anti-Raid Özelliği Aktif Edilmiş İse Botu Sunucuya Yeniden Almak İçin Kullanılır.")
.addField("!ban [kullanıcı] (sebep)", "Kullanıcıyı Sunucudan Banlar.")
.addField("!banlananlar" , "Sunucudan Banlananları Gösterir.")
.addField("!başvuru", "Başvuru Yapmak İçin Kullanılır.")
.addField("!bot-isim [botetiket] [yenisim]", "Sunucunuzda Bot İsimlerini Değiştirir.")
.addField("!capslock-engelleme (aç/kapat)", "Kanalda Büyük Harf Kullanımını Engeller.")
.addField("!davet-sıralaması", "Sunucuda En Çok Davet Yapan Kişileri Gösterir.")
.addField("!üyemesaj [kullanıcı]" , "Kullanıcıya Bot Tarafından Mesaj Gönderilir.")
.addField("!dmduyuru" , "Özel Mesajdan Duyuru Yapar.")
.addField("!duyuru (duyuru mesajı)" , "Bulunduğunuz Kanalda Duyuru Yapar.")
.addField("!embedliyaz [mesaj]" , "Kanala Embedli Yazı Yazar.")
.addField("!emojiekle [link]" , "Sunucuya Link İle Emoji Ekler.")
.addField("!forceban [id]" , "Id İle Ban Atar.")
.addField("!güvenlik-ayarla [#kanalismi]" , "Güvenlik Kanalı Ayarlar.")
.addField("!güvenlik-kaldır [#kanalismi]" , "Güvenlik Kanalını Siler.")
.addField("!hazır-kanallar" , "Sunucuda Gerekli Hazır Kanalları Yaratır.")
.addField("!herkeserolver [@rol]" , "Herkese Belirttiğiniz Rolü Verir.")
.addField("!herkesdenrolal" , "Herkesten Belirttiğiniz Rolü Alır.")
.addField("!hgbb-ayarla [#kanal]" , "Resimsiz Hoşgeldin-BB Kanalını Ayarlar.")
.addField("!kilit [#kanal] [süre] " , "Belirttiğiniz Kanalı Belirttiğiniz Süre Kadar Kilitler.")
.addField("!kick [kullanıcı] " , "Kullanıcıyı Sunucudan Atar.")
.addField("!küfürengel (aç/kapat)" , "Küfür Engel Sistemini Açar.")
.addField("!mute [kullanıcı] " , "Kullanıcıyı Sunucuda Muteler.")
.addField("!otorol [@rol] [#kanal]" , "Otorol Sistemini Aktif Eder.")
.addField("!otorolkapat" , "Otorol Sistemini Kapatır.")
.addField("!oylama" , "Oylama Yapar.")
.addField("!random" , "Sunucuda Herhangi Bir Kişiyi Çıkarır(Çekiliş İçin Kullanılabilir.).")
.addField("!reklamengel (aç/kapat)" , "Reklam Engel Sistemini Açar.")
.addField("!reklamkick (aç/kapat)" , "Reklam Kick Özelliğini Açar.")
.addField("!resimlihg-ayarla [#kanal]" , "Resimli Hoş Geldin Sistemini Ayarlar.")
.addField("!rol-koruma (aç/kapat)" , "Rol Koruma Sistemini Açar.")
.addField("!sa-as (aç/kapat)" , "Selam Sistemini Açar.")
.addField("!sayaç [#kanal]" , "Sayaç Sistemini Ayarlar.")
.addField("!sayaç-kapat" , "Sayaç Sistemini Kapatır.")
.addField("!sayaç-sustur [kullanıcı] [süre]" , "Kullanıcıyı Seslide Sustur.")
.addField("!sesli-çekiliş" , "Sesli Kanaldakiler Arasında Çekiliş Yapar.")
.addField("!sil [mesajsayısı]" , "Mesajları Siler.")
.addField("!yavaşmod [süre]" , "Kanalda Yavaş Mod Aktifleştirir.")
.addField("!snipe" , "Son Silinen Mesajı Gösterir.")
.addField("!soft-ban [kullanıcı]" , "SoftBan: Kullanıcıyı Banlar Ve Geri Banını Açar.")
.addField("!tempmute [kullanıcı] [süre]" , "Süreli Olarak Mute Atar.")
.addField("!mute-log-ayarla [#kanal]" , "Mute Log Kanalını Ayarlar.")
.addField("!çek [kullanıcı]" , "Kullanıcıyı Bulunduğunuz Sesli Kanala Çeker.")
.addField("!unban [kullanıcıid]" , "Kullanıcının Banını Açar.")
.addField("!unbanall" , "Tüm Banları Kaldırır.")
.addField("!unmute [kullanıcı]" , "Kullanıcının Mutesini Açar.")
.addField("!uyar [kullanıcı]" , "Kullanıcıyı Uyarır.")
.addField("!votekick [kullanıcı]" , "Kullanıcıy Oylama İle Kickler.")
.addField("!yaz [mesaj]" , "Bota Mesaj Yazdırırsınız.")
.addField("!çekiliş [çekilişyapılıcakmesaj]" , "Çekiliş Yapmaya Yarar.")

message.channel.sendEmbed(mhelp)
.then; const sembed = new Discord.RichEmbed()
.setTitle(" Search Plugin Commands ")
.setColor("#5ab1bb")
.setThumbnail("https://images-ext-2.discordapp.net/external/v0edFI9oWuSe523E3IDXT_4vIpQKHXg3ExG2SH6UwK4/https/i.imgur.com/4e2Rnwq.png")
.addField(" !anime [search] ", "Search for any anime on Kitsu.io")
.addField("!imgur [search]","Search for memes on imgur.com")
.addField("!manga [search]","Search for any manga on Kitsu.io")
.addField("!pokemon [search]","Search for any pokémon on the pokéapi pokédex")
.addField("!twitch [search]","Search for any streamer on Twitch.tv")
.addField("!urban [search]","Search for slang words on the Urban Dictionnary")
.addField("!youtube [search]","Search for YouTube videos")
message.channel.sendEmbed(sembed)
.then; const blindhelp = new Discord.RichEmbed()
.setThumbnail("https://i.imgur.com/ZUlvtW0.png")
.setColor("#5ab1bb")
.setTitle("Blindtest Plugin Commands")
.addField("!start-quiz","Starts a Music Quiz game in your voice channel")
.addField("!stop-quiz","Stops the current Music Quiz game")
message.channel.sendEmbed(blindhelp)
.then; const musichelp = new Discord.RichEmbed()
.setTitle("Music Plugin Commands")
.setColor("#5ab1bb")
.setThumbnail("https://i.imgur.com/1J243X9.png")
.addField("!add [search]","Add a music to the playlist")
.addField("!join","Joins the user voice channel")
.addField("!leave","Leaves current voice channel")
.addField("!play (optional search)","Adds the song to the queue and plays it if the queue is empty")
.addField("!queue","Display the current queue")
.addField("!search [search]","Searches for a song that can be later added to the queue")
.addField("!stop","Stops the current playing song and leaves the voice channel")
.addField("!vote-skip","Starts a vote to skip to the next song")
message.channel.sendEmbed(musichelp)
.then; const recohelp = new Discord.RichEmbed()
.setTitle("Record Plugin Commands")
.setColor("#5ab1bb")
.setThumbnail("https://i.imgur.com/4UjvHCp.png")
.addField("!record","Joins your voice channel and starts a recording")
.addField("!stop-recording","Stops the current recording")
message.channel.sendEmbed(recohelp)
};
exports.conf = {
    enabled: true, 
    guildOnly: false, 
    aliases: [], 
    permLevel: 0 
  };
  
  exports.help = {
    name: 'mcat', 
    description: 'The Help Command',
    usage: 'mcat'
  };